version: '3.0'
services:
  db:
    image: postgres
    container_name: Database
    ports:
      - "5432:5432"
    volumes:
      - "./docker/db/pgdata:/var/lib/postgresql/data"
    networks:
      - rede-virtual-2
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "challenge"

  api:
    container_name: backEnd
    depends_on:
      - db
    links:
      - db
    build: '.'
    networks:
      - rede-virtual-2
    ports:
      - "8000:8000"
networks:
      rede-virtual-2: