# Generated by Django 3.2 on 2022-11-24 22:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propertie',
            fields=[
                ('property_code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='property code')),
                ('limit_guests', models.IntegerField(blank=True, null=True, verbose_name='guests limit')),
                ('bathroom_quantity', models.IntegerField(blank=True, null=True, verbose_name='bathrooms quantity')),
                ('accept_animal', models.BooleanField(default=False, verbose_name='accept animals')),
                ('housekeeping_price', models.FloatField(blank=True, null=True, verbose_name='housekeeping price')),
                ('activate_date', models.DateField(blank=True, null=True, verbose_name='activate date')),
                ('created_at', models.DateTimeField(auto_now=True, null=True, verbose_name='createdAt')),
                ('update_at', models.DateTimeField(auto_now=True, null=True, verbose_name='updatedAt')),
            ],
        ),
    ]
