# Generated by Django 3.2 on 2022-11-24 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imoveis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='platform name')),
                ('platform_tax', models.FloatField(blank=True, null=True, verbose_name='platform tax')),
                ('created_at', models.DateTimeField(auto_now=True, null=True, verbose_name='createdAt')),
                ('update_at', models.DateTimeField(auto_now=True, null=True, verbose_name='updatedAt')),
                ('property_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imoveis.propertie', verbose_name='property code')),
            ],
        ),
    ]
