# Generated by Django 3.2 on 2022-11-24 22:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anuncios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='reservation code')),
                ('guests', models.IntegerField(blank=True, null=True, verbose_name='number of guests')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='comments')),
                ('total_price', models.FloatField(blank=True, null=True, verbose_name='total price')),
                ('check_in', models.DateField(blank=True, null=True, verbose_name='check-in')),
                ('check_out', models.DateField(blank=True, null=True, verbose_name='check-out')),
                ('created_at', models.DateTimeField(auto_now=True, null=True, verbose_name='createdAt')),
                ('update_at', models.DateTimeField(auto_now=True, null=True, verbose_name='updatedAt')),
                ('ads_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anuncios.ad', verbose_name='ads code')),
            ],
        ),
    ]
